language: generic

sudo: required
services:
  - docker

before_install: 
  - docker build -t dyaron77/docker-react -f Dockerfile.dev .

script:
  - docker run dyaron77/docker-react npm run test -- --coverage 
  # - docker run -e CI=true dyaron77/docker-react npm run test